spring.application.name=pet-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/pet_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

notification.service.url=http://localhost:8084
frontend.service.url=http://localhost:8080

# Logging
logging.level.main=INFO
