spring.application.name=frontend-service
server.port=8080


# Other services
auth.service.url=http://localhost:8083
pet.service.url=http://localhost:8081
item.service.url=http://localhost:8082
export.service.url=http://localhost:8085

# Thymeleaf
spring.thymeleaf.cache=false
# WebSocket endpoint on pet-service
pet.service.ws.url=http://localhost:8081

# i18n
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8

# Logging
logging.level.main=INFO